[package]
name = "announcer_bot"
version = "0.2.1"
authors = ["sasjafor <john93412@gmail.com>"]

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
libsodium-sys = "0.2.5"
url = "2.1.1"
regex = "1.3.9"
lazy_static = "1.4.0"
rusqlite = "0.23.1"

[dependencies.serenity]
default-features = false
features = [
    "builder",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "cache",
    "voice",
    "native_tls_backend",
]
version = "0.8.6"
