[package]
name = "announcer_bot"
version = "0.1.0"
authors = ["sasjafor <john93412@gmail.com>"]

[dependencies]
log = "0.4.6"
env_logger = "0.6.1"

[dependencies.serenity]
default-features = false
features = [
    "builder",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "cache",
    "voice",
]
git = "https://github.com/serenity-rs/serenity"
rev = "722e1cc"
