name: Get latest release version
on:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/ytdl-org/youtube-dl/releases/latest | \
          jq -r ".tag_name" > .release-versions/youtube-dl-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version & trigger docker build
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'sasjafor'
          git config --global user.email 'sascha.forster@hotmail.ch'
          git commit -am "New release version"
          git push
          curl -X POST https://hub.docker.com/api/build/v1/source/ea8bc9b3-f0c8-4df9-905e-7a25213f7312/trigger/20bca522-9907-4ab3-8824-2aefcb5a25b9/call/
        
